name: requests2
description: a flutter library that helps with http requests and stored cookies
version: 4.0.0-nullsafety.0
homepage: https://github.com/imdatsolak/requests2
authors:
- Jossef Harush <jossef12@gmail.com>
- Rick Stanley <rick-stanley@hotmail.com>
- Martin <https://github.com/genesiscz>
- Frederik Pietzko <pietzkof@gmail.com>
- Rafael Carvalho Monteiro <rafael@qwkin.io>
- eggate <https://github.com/eggate>
- Dane Mackier <https://github.com/FilledStacks>
- Anirudh S <https://github.com/anirudh24seven>
- Imdat Solak <imdat@solak.de>
- obuhovsergai <https://github.com/obuhovsergai>
- Ian Koerich Maciel <https://github.com/ianmaciel>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  shared_preferences: ^2.0.5
  crypto: ^3.0.0
  hex: ^0.2.0
  logging: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.0.0

